"""Browser-storage, reduced-motion, dialog and unavailable-WebGL fallbacks."""
from pathlib import Path
import json
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True,args=['--use-angle=metal','--enable-gpu'])
    context = browser.new_context(viewport={'width':320,'height':568},is_mobile=True,has_touch=True,reduced_motion='reduce')
    context.grant_permissions(['clipboard-read','clipboard-write'], origin='http://127.0.0.1:5114')
    context.add_init_script("Object.defineProperty(window, 'localStorage', {get(){throw new DOMException('Unavailable','SecurityError')}})")
    page = context.new_page(); errors=[]
    page.on('pageerror',lambda error: errors.append(str(error)))
    page.goto('http://127.0.0.1:5114/3d-lab.html',wait_until='networkidle')
    page.get_by_role('button',name='Challenge requirements and levels',exact=True).tap()
    page.get_by_role('button',name='Free DIY',exact=True).tap()
    page.get_by_role('button',name='Material collection and rewards',exact=True).tap()
    for _ in range(3): page.get_by_role('button',name='Add Cloud pearl',exact=True).tap()
    page.get_by_role('button',name='Close bead collection',exact=True).tap()
    expect(page.locator('[data-lab-shell]')).to_have_attribute('data-storage','unavailable')
    page.locator('[data-action="finish"]').tap()
    page.get_by_role('button',name='Customize & shop',exact=True).tap()
    page.locator('summary').click()
    page.locator('[data-action="download-list"]').scroll_into_view_if_needed()
    page.get_by_role('button',name='Copy list',exact=True).tap()
    expect(page.locator('[data-custom-status]')).to_contain_text('List copied')
    assert 'Cloud pearl × 3' in page.evaluate('navigator.clipboard.readText()')
    expect(page.get_by_role('button',name='Close customization',exact=True)).to_be_in_viewport()
    page.screenshot(path=str(Path(__file__).resolve().parents[1] / 'evidence/styling-v7/sticky-close.png'))
    page.get_by_role('button',name='Close customization',exact=True).tap()
    page.get_by_role('button',name='Edit',exact=True).tap()
    page.get_by_role('button',name='Shop settings',exact=True).tap()
    page.get_by_label('Shop link',exact=True).fill('https://shop.example.com/')
    page.get_by_role('button',name='Save links',exact=True).tap()
    expect(page.locator('[data-shop-status]')).to_contain_text('Links were not saved')
    assert not errors,errors
    context.close()
    context=browser.new_context(viewport={'width':390,'height':844})
    context.add_init_script("const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type,...args){if(type==='webgl'||type==='webgl2')return null;return original.call(this,type,...args)}")
    page=context.new_page()
    page.goto('http://127.0.0.1:5114/3d-lab.html',wait_until='networkidle')
    expect(page.locator('[data-lab-shell]')).to_have_attribute('data-mode','2d')
    expect(page.get_by_role('button',name='Challenge requirements and levels',exact=True)).not_to_be_visible()
    page.get_by_role('link',name='Open 2D studio').click()
    expect(page.locator('[data-action="start"]')).to_be_visible()
    page.locator('[data-action="start"]').click()
    expect(page.locator('[data-view="compose"]')).to_be_visible()
    context.close();browser.close()
    print(json.dumps({'result':'pass','checks':['storage-unavailable','reduced-motion-compose','clipboard-copy','sticky-close-320','no-false-save','webgl-fallback','2d-entry']}),flush=True)
