import { rewardItem,ownedIds } from './collection-game.js';
import { createGravityRound,dropAccessory,stepGravity,accessoryType,unlockPoints,earnedUnlockPoints,remainingUnlockPoints,FIELD_WIDTH,FIELD_HEIGHT } from './gravity-game.js';
import { openDialog } from './studio-ui.js';
import { ICE_BLUE_MODULES, claimMainlineClear, mainlineStep, nextMainlineModule, normalizeMainline } from './ice-blue-mainline.js';
import { mountReward3D } from './reward-3d-viewer.js';

const icon=(path)=>`<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="21"/>${path}</svg>`;
export function impactOptions(impact){
  if(!impact)return{intensity:0,x:.5};
  return{intensity:Math.max(0,Math.min(1,Number(impact.intensity)||0)),materialFamily:impact.materialFamily,materialPair:impact.materialPair,x:Math.max(0,Math.min(1,impact.x/FIELD_WIDTH))};
}
export function createRoundScheduler(){
  const pending=new Set();let paused=false;
  function arm(task){task.startedAt=performance.now();task.timer=setTimeout(()=>{pending.delete(task);task.run();},task.remaining);}
  return{
    schedule(run,delay){const task={run,remaining:delay,timer:0,startedAt:0};pending.add(task);if(!paused)arm(task);},
    pause(){if(paused)return;paused=true;for(const task of pending){clearTimeout(task.timer);task.remaining=Math.max(0,task.remaining-(performance.now()-task.startedAt));}},
    resume(){if(!paused)return;paused=false;for(const task of pending)arm(task);},
    clear(){for(const task of pending)clearTimeout(task.timer);pending.clear();},
  };
}
export function createCollectionUI({shell,getCollection,setCollection,getArt,beforeOpen,sound}){
  const dialog=document.createElement('dialog');dialog.className='studio-dialog match-dialog gravity-dialog';dialog.dataset.dialog='match';dialog.setAttribute('aria-labelledby','match-title');
  dialog.innerHTML=`<picture class="gravity-art-base" aria-hidden="true"><source srcset="/assets/gravity-tray-base-v30.webp" type="image/webp"><img src="/assets/gravity-tray-base-v30.png" alt=""></picture><picture class="gravity-art-hud" aria-hidden="true"><source srcset="/assets/gravity-tray-hud-v30.webp" type="image/webp"><img src="/assets/gravity-tray-hud-v30.png" alt=""></picture><header><button type="button" data-match-back aria-label="Return to DIY"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg></button><h2 id="match-title" class="visually-hidden">Accessory drop</h2><div class="gravity-mark" aria-hidden="true"><i></i><i></i><i></i></div><button type="button" data-match-sound aria-label="Mute soundtrack"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V6l10-2v12"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></svg></button></header>
  <div data-match-ready class="match-intro gravity-intro"><div class="prize-image"><img data-prize-image alt=""></div><h3 data-prize-name class="visually-hidden"></h3><p data-prize-rule class="visually-hidden"></p><div class="match-gesture" aria-hidden="true"><i></i><i></i><i></i><b></b></div><button type="button" class="icon-cta" data-match-start aria-label="Play">${icon('<path d="m20 15 14 9-14 9Z"/>')}</button></div>
  <section data-match-play hidden class="gravity-play" aria-label="Falling accessory game"><div class="gravity-hud"><div class="gravity-goal" data-gravity-goal-wrap><img data-gravity-goal alt=""><i></i></div><div class="gravity-next" data-gravity-next aria-label="Next accessories"></div><div class="gravity-time" data-gravity-time aria-label="60 seconds remaining">60</div><div class="gravity-points" data-gravity-points role="status" aria-live="polite"><span aria-hidden="true">✦</span><strong data-gravity-remaining>1500</strong><small><b data-gravity-earned>0</b>/<b data-gravity-point-target>1500</b></small></div></div><div class="gravity-progress"><i></i></div><div class="gravity-field" data-gravity-field role="application" aria-label="Tap inside the tray to drop an accessory"><div class="danger-line"></div><div class="drop-beam" data-drop-beam></div><canvas class="gravity-seed-canvas" data-gravity-seed-canvas aria-hidden="true"></canvas><div class="gravity-pieces" data-gravity-pieces></div><div class="gravity-effects" data-gravity-effects aria-hidden="true"></div><div class="gravity-tap" aria-hidden="true"><i></i></div></div><p data-match-feedback class="visually-hidden" role="status"></p><span data-gravity-cleared class="visually-hidden"></span><span data-gravity-target class="visually-hidden"></span><span data-gravity-score class="visually-hidden"></span></section>
  <section data-match-end hidden class="match-reveal"><canvas class="reward-world" data-reward-3d aria-label="Drag to rotate the 3D charm" hidden></canvas><div class="unlock-world" aria-hidden="true"><i class="unlock-depth"></i><i class="unlock-beam"></i><i class="unlock-ring"></i><i class="unlock-flare"></i></div><div class="reveal-stage"><div class="reveal-aura"></div><div class="reveal-sparks">${'<i></i>'.repeat(20)}</div><div class="prize-image reveal-prize"><div data-reward-frame><img data-end-image alt=""></div></div><small class="drag-hint">左右拖动 · 360° 查看</small></div><div class="unlock-title"><p data-end-label></p><h3 data-end-name></h3></div><div class="coupon-ticket" data-coupon-ticket hidden><small>本次盲盒奖励</small><strong data-coupon-value>¥5</strong><em>已收入卡包</em></div><p data-end-copy role="status"></p><div class="match-end-actions"><button type="button" class="icon-cta" data-match-again aria-label="再挑战一次">${icon('<path d="M33 20a10 10 0 1 0 0 8m0-13v7h-7"/>')}</button><button type="button" class="icon-cta" data-match-shop aria-label="查看商品">${icon('<path d="M14 18h20l-2 17H16Zm5 0a5 5 0 0 1 10 0"/>')}</button></div></section>`;
  shell.append(dialog);const $=s=>dialog.querySelector(s);let round=null,rewardId=null,raf=0,lastFrame=0,lastDrop=0,resolved=false,phase='ready',nextSignature='',hudSignature='',rewardViewer=null,pausedAnimations=[];const nodes=new Map(),seedImages=new Map(),originalSound=shell.querySelector('[data-action="sound"]'),timers=createRoundScheduler();
  function syncSound(){const muted=originalSound.getAttribute('aria-pressed')==='true';$('[data-match-sound]').setAttribute('aria-pressed',String(muted));$('[data-match-sound]').setAttribute('aria-label',muted?'Turn on soundtrack':'Mute soundtrack');}new MutationObserver(syncSound).observe(originalSound,{attributes:true,attributeFilter:['aria-pressed']});syncSound();
  function stop(){cancelAnimationFrame(raf);raf=0;lastFrame=0;timers.clear();rewardViewer?.destroy();rewardViewer=null;sound.stopReveal?.();pausedAnimations.forEach(animation=>animation.play());pausedAnimations=[];dialog.classList.remove('is-entering');$('[data-gravity-field]').classList.remove('is-clearing','is-impacting');$('[data-gravity-field]').querySelectorAll('.chain-label').forEach(node=>node.remove());}
  function setActionsReady(ready){$('.match-end-actions').inert=!ready;$('[data-match-again]').disabled=!ready;$('[data-match-shop]').disabled=!ready;}
  function setPhase(next){phase=next;dialog.dataset.gameState=next;$('[data-match-ready]').hidden=next!=='ready';$('[data-match-play]').hidden=next!=='playing';$('[data-match-end]').hidden=next!=='won'&&next!=='lost';}
  const art=type=>getArt().urls.get(accessoryType(type).artId);
  function renderNext(){const signature=round.nextTypes.join('|');if(signature===nextSignature)return;nextSignature=signature;$('[data-gravity-next]').replaceChildren(...round.nextTypes.map((type,index)=>{const img=new Image();img.src=art(type);img.dataset.material=type;img.alt=index?`${accessoryType(type).shape} later`:`Next ${accessoryType(type).shape}`;return img;}));}
  function seedImage(type){if(seedImages.has(type))return seedImages.get(type);const image=new Image();image.decoding='async';image.onload=()=>{if(round&&phase==='playing')renderSeeds();};image.src=art(type);seedImages.set(type,image);return image;}
  function renderSeeds(){
    const canvas=$('[data-gravity-seed-canvas]'),width=canvas.clientWidth,height=canvas.clientHeight,dpr=Math.min(2,devicePixelRatio||1);
    if(!width||!height)return;
    const pixelWidth=Math.round(width*dpr),pixelHeight=Math.round(height*dpr);
    if(canvas.width!==pixelWidth||canvas.height!==pixelHeight){canvas.width=pixelWidth;canvas.height=pixelHeight;}
    const context=canvas.getContext('2d',{alpha:true});context.setTransform(dpr,0,0,dpr,0,0);context.clearRect(0,0,width,height);
    const scaleX=width/FIELD_WIDTH,scaleY=height/FIELD_HEIGHT,sizeScale=Math.min(scaleX,scaleY);context.imageSmoothingEnabled=true;
    for(const p of round.pieces){if(!p.seeded)continue;const image=seedImage(p.type);if(!image.complete||!image.naturalWidth)continue;const size=p.radius*2*sizeScale;context.save();context.translate(p.x*scaleX,p.y*scaleY);context.rotate(p.rotation);context.drawImage(image,-size/2,-size/2,size,size);context.restore();}
  }
  function render(){if(!round)return;renderSeeds();const field=$('[data-gravity-field]'),fieldRect=field.getBoundingClientRect(),sizeScale=Math.min(fieldRect.width/FIELD_WIDTH,fieldRect.height/FIELD_HEIGHT),live=new Set(round.pieces.filter(p=>!p.seeded).map(p=>p.id));for(const[id,node]of nodes)if(!live.has(id)){node.remove();nodes.delete(id);}for(const p of round.pieces){if(p.seeded)continue;let node=nodes.get(p.id);if(!node){const url=art(p.type);node=document.createElement('span');node.className='gravity-piece';node.dataset.type=p.shape;node.dataset.material=p.type;node.dataset.seeded='false';node.setAttribute('aria-hidden','true');node.innerHTML='<i class="gravity-piece-shadow"></i><img class="gravity-piece-depth" alt="" draggable="false"><img class="gravity-piece-face" alt="" draggable="false"><i class="gravity-piece-glint"></i>';node.querySelectorAll('img').forEach(img=>img.src=url);const glint=node.querySelector('.gravity-piece-glint');glint.style.webkitMaskImage=`url("${url}")`;glint.style.maskImage=`url("${url}")`;$('[data-gravity-pieces]').append(node);nodes.set(p.id,node);}node.dataset.motion=p.settled>180?'settled':'falling';node.style.left=`${p.x/FIELD_WIDTH*100}%`;node.style.top=`${p.y/FIELD_HEIGHT*100}%`;node.style.width=`${p.radius*2*sizeScale}px`;node.style.setProperty('--tilt-x',`${Math.min(13,Math.abs(p.vy)*19)}deg`);node.style.setProperty('--tilt-y',`${Math.max(-13,Math.min(13,p.vx*210))}deg`);node.style.setProperty('--speed',String(Math.min(1,Math.hypot(p.vx,p.vy)*1.6)));node.style.transform=`translate(-50%,-50%) rotate(${p.rotation}rad)`;}field.dataset.pieceCount=String(round.pieces.length);field.dataset.seededCount=String(round.pieces.filter(p=>p.seeded).length);const earned=earnedUnlockPoints(round),target=unlockPoints(round),remaining=remainingUnlockPoints(round),progress=Math.min(100,earned/target*100),seconds=Math.max(0,Math.ceil(round.remainingMs/1000)),signature=`${earned}|${target}|${round.dangerY}|${seconds}`;if(signature!==hudSignature){hudSignature=signature;$('[data-gravity-cleared]').textContent=String(round.cleared);$('[data-gravity-target]').textContent=String(target);$('[data-gravity-score]').textContent=String(round.score);$('[data-gravity-earned]').textContent=String(earned);$('[data-gravity-point-target]').textContent=String(target);$('[data-gravity-remaining]').textContent=String(remaining);$('[data-gravity-time]').textContent=String(seconds);$('[data-gravity-time]').setAttribute('aria-label',`${seconds} seconds remaining`);$('[data-gravity-points]').setAttribute('aria-label',`${remaining} points until unlock`);$('.gravity-progress i').style.width=`${progress}%`;$('.gravity-progress').style.setProperty('--progress',`${progress}%`);$('[data-gravity-goal-wrap]').style.setProperty('--goal',`${progress*3.6}deg`);field.style.setProperty('--danger-top',`${round.dangerY/FIELD_HEIGHT*100}%`);}renderNext();}
  function burst(removed,chain){const field=$('[data-gravity-field]'),effects=$('[data-gravity-effects]'),cx=removed.reduce((sum,p)=>sum+p.x,0)/removed.length,cy=removed.reduce((sum,p)=>sum+p.y,0)/removed.length;field.dataset.chain=String(chain);field.classList.remove('is-clearing');void field.offsetWidth;field.classList.add('is-clearing');timers.schedule(()=>field.classList.remove('is-clearing'),430);const wave=document.createElement('span');wave.className='gravity-wave';wave.style.left=`${cx/FIELD_WIDTH*100}%`;wave.style.top=`${cy/FIELD_HEIGHT*100}%`;wave.style.setProperty('--wave-scale',String(7+Math.min(4,chain)*1.4));effects.append(wave);timers.schedule(()=>wave.remove(),760);for(const p of removed){const b=document.createElement('span');b.className='gravity-burst';b.style.left=`${p.x/FIELD_WIDTH*100}%`;b.style.top=`${p.y/FIELD_HEIGHT*100}%`;const count=8+Math.min(3,chain)*2;for(let index=0;index<count;index++){const spark=document.createElement('i'),angle=Math.PI*2*index/count,distance=30+chain*7+(index%2)*9;spark.style.setProperty('--gx',`${Math.cos(angle)*distance}px`);spark.style.setProperty('--gy',`${Math.sin(angle)*distance}px`);spark.style.setProperty('--delay',`${index*7}ms`);b.append(spark);}effects.append(b);timers.schedule(()=>b.remove(),720);}if(chain>1){const label=document.createElement('strong');label.className='chain-label';label.setAttribute('aria-hidden','true');label.innerHTML='<i></i>'.repeat(Math.min(5,chain+2));field.append(label);timers.schedule(()=>label.remove(),720);}}
  function showResult(){if(resolved||!round||phase!=='resolving'||!dialog.open)return;resolved=true;stop();const won=round.status==='won',result=won?claimMainlineClear(getCollection().mainline):null;if(result){setCollection({...getCollection(),mainline:result.state});rewardId=result.module?.id||rewardId;}setPhase(won?'won':'lost');dialog.classList.toggle('is-reveal',won);dialog.dataset.granted=String(Boolean(result?.module));const item=rewardItem(rewardId),image=$('[data-end-image]'),canvas=$('[data-reward-3d]');image.src=getArt().urls.get(rewardId);image.alt=item?.name||'Ice blue charm';image.hidden=false;canvas.hidden=true;$('[data-end-label]').textContent=won?(result.module?'冰蓝星梦 · 新收藏':'冰蓝星梦 · 全系列'):'挑战未完成';$('[data-end-name]').textContent=won?(result.module?.name||'再次获得优惠券'):'再试一次';$('[data-coupon-ticket]').hidden=!won;$('[data-coupon-value]').textContent=won?`¥${result.coupon.value}`:'';$('[data-end-copy]').textContent=won?'挂件与优惠券已同时收入收藏。':'已解锁的挂件和优惠券都会保留。';$('[data-match-shop]').hidden=!won;const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;setActionsReady(!won||reducedMotion);if(won){canvas.hidden=false;rewardViewer=mountReward3D(canvas,{id:rewardId,reducedMotion,frameElement:$('[data-reward-frame]'),onReady:()=>{image.hidden=true;canvas.hidden=false;},onError:()=>{canvas.hidden=true;image.hidden=false;}});sound.play('unlock-theme',rewardId);timers.schedule(()=>phase==='won'&&sound.play('coupon-reveal',rewardId),reducedMotion?0:2640);timers.schedule(()=>{if(phase!=='won')return;setActionsReady(true);$('[data-match-again]').focus();},reducedMotion?0:3670);}else{sound.play('retry',rewardId);$('[data-match-again]').focus();}}
  function contactPulse(impact){
    if(!impact||impact.intensity<.06)return;
    const field=$('[data-gravity-field]');field.dataset.impactFamily=impact.materialFamily;field.dataset.impactIntensity=String(impact.intensity);field.dataset.impactCount=String(Number(field.dataset.impactCount||0)+1);
    const effects=$('[data-gravity-effects]');
    if(effects.querySelectorAll('.contact-pulse').length>=5)return;
    const pulse=document.createElement('i');pulse.className='contact-pulse';pulse.dataset.material=impact.materialFamily;
    pulse.style.left=`${Math.max(0,Math.min(100,impact.x/FIELD_WIDTH*100))}%`;
    pulse.style.top=`${Math.max(0,Math.min(100,impact.y/FIELD_HEIGHT*100))}%`;
    pulse.style.setProperty('--contact-size',`${9+impact.intensity*17}px`);
    pulse.style.setProperty('--contact-alpha',String(.15+impact.intensity*.35));
    effects.append(pulse);timers.schedule(()=>pulse.remove(),240);
  }
  function frame(now){raf=0;if(phase!=='playing'||document.hidden||!dialog.open)return;const result=stepGravity(round,lastFrame?now-lastFrame:16);lastFrame=now;round=result.round;if(result.event==='clear'){burst(result.removed,round.chain);sound.play('match',result.removed[0]?.artId||rewardId,round.chain);$('[data-match-feedback]').textContent=round.chain>1?`Cascade ${round.chain}`:`${result.removed.length} accessories cleared`;}else if(result.event==='impact'){contactPulse(result.impact);sound.play('impact',result.artId||rewardId,1,impactOptions(result.impact));}render();if(round.status!=='playing'){phase='resolving';dialog.dataset.gameState='resolving';timers.schedule(showResult,round.status==='won'?650:220);return;}raf=requestAnimationFrame(frame);}
  function start(){stop();resolved=false;lastDrop=0;nextSignature='';hudSignature='';const state=normalizeMainline(getCollection().mainline),next=nextMainlineModule(state);rewardId=next?.id||ICE_BLUE_MODULES.at(-1).id;dialog.dataset.rewardId=rewardId;$('[data-gravity-goal]').src=getArt().urls.get(rewardId);$('[data-gravity-goal]').alt=`Unlock ${rewardItem(rewardId).name}`;round=createGravityRound(rewardId,Math.random,ownedIds(getCollection()),mainlineStep(state)+1);nodes.clear();$('[data-gravity-pieces]').replaceChildren();$('[data-gravity-effects]').replaceChildren();$('.gravity-tap').hidden=false;setPhase('playing');dialog.dataset.level=String(round.level);dialog.classList.remove('is-reveal');dialog.classList.add('is-entering');timers.schedule(()=>dialog.classList.remove('is-entering'),1250);$('[data-match-feedback]').textContent='Three matching accessories clear.';render();sound.play('select');raf=requestAnimationFrame(frame);$('[data-gravity-field]').focus({preventScroll:true});}
  function open(id,{startImmediately=false}={}){if(!getArt())return false;beforeOpen();stop();round=null;resolved=false;const next=nextMainlineModule(getCollection().mainline);rewardId=next?.id||ICE_BLUE_MODULES.at(-1).id;dialog.dataset.rewardId=rewardId;dialog.dataset.granted='false';dialog.classList.remove('is-reveal');const item=rewardItem(rewardId),url=getArt().urls.get(rewardId);$('[data-prize-image]').src=url;$('[data-prize-image]').alt=item.name;$('[data-gravity-goal]').src=url;$('[data-gravity-goal]').alt=`Unlock ${item.name}`;$('[data-prize-name]').textContent=item.name;$('[data-prize-rule]').textContent=next?'三连消除，通关解锁一个完整挂件与优惠券盲盒。':'系列已集齐，通关继续抽优惠券盲盒。';$('[data-match-start]').setAttribute('aria-label','开始挑战');setPhase('ready');if(!dialog.open)openDialog('match');if(startImmediately)start();return true;}
  function dropAt(event){if(phase!=='playing'||performance.now()-lastDrop<round.dropCooldown)return;const field=$('[data-gravity-field]'),rect=field.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*FIELD_WIDTH;round=dropAccessory(round,x);lastDrop=performance.now();render();sound.play('pickup',round.pieces.at(-1)?.artId);$('.gravity-tap').hidden=true;}
  const field=$('[data-gravity-field]');let keyboardAim=50;field.tabIndex=0;field.setAttribute('aria-label','Drop an accessory: tap the tray, or use Left and Right arrows then Space or Enter.');field.addEventListener('pointermove',event=>{const rect=field.getBoundingClientRect();keyboardAim=Math.max(4,Math.min(96,(event.clientX-rect.left)/rect.width*100));$('[data-drop-beam]').style.left=`${keyboardAim}%`;});field.addEventListener('pointerup',dropAt);field.addEventListener('keydown',event=>{if(phase!=='playing'||!['ArrowLeft','ArrowRight',' ','Enter'].includes(event.key))return;event.preventDefault();if(event.key==='ArrowLeft'||event.key==='ArrowRight'){keyboardAim=Math.max(4,Math.min(96,keyboardAim+(event.key==='ArrowLeft'?-8:8)));$('[data-drop-beam]').style.left=`${keyboardAim}%`;}else if(!event.repeat){const rect=field.getBoundingClientRect();dropAt({clientX:rect.left+rect.width*keyboardAim/100});}});
  dialog.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-match-back'))dialog.close();else if(b.hasAttribute('data-match-sound'))originalSound.click();else if(b.hasAttribute('data-match-start')||b.hasAttribute('data-match-again'))start();else if(b.hasAttribute('data-match-shop'))window.open(normalizeMainline(getCollection().mainline).productUrl,'_blank','noopener');});dialog.addEventListener('close',()=>{if(dialog.open)return;stop();round=null;phase='closed';dialog.dataset.gameState='closed';});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;lastFrame=0;timers.pause();rewardViewer?.pause();pausedAnimations=(dialog.getAnimations?.({subtree:true})||[]).filter(animation=>animation.playState==='running');pausedAnimations.forEach(animation=>animation.pause());}else{timers.resume();pausedAnimations.forEach(animation=>animation.play());pausedAnimations=[];if(dialog.open){rewardViewer?.resume();if(phase==='playing'&&!raf)raf=requestAnimationFrame(frame);}}});return{open,openAndStart:id=>open(id,{startImmediately:true})};
}
